FROM python:3.10

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

COPY requirements.txt requirements.txt

RUN pip install --no-cache-dir --upgrade -r requirements.txt --use-deprecated=legacy-resolver

COPY ./tests /tests
COPY ./project /project

WORKDIR /tests

USER root:root

CMD ["pytest", "-c", "pytest.ini"]