services:
  tests:
    build:
      dockerfile: Dockerfile-tests
      context: .
    restart: "no"
    depends_on:
      - tests-db
      - tests-redis
    env_file:
      - .env.tests
    links:
      - tests-redis
      - tests-db
    volumes:
      - ${MEDIA_PATH}:/var/bgram_tests/media
    networks:
      - test-app-network
  tests-db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - PGPORT=5433
    env_file:
      - .env.tests
    expose:
      - '5433'
    networks:
      - test-app-network
  tests-redis:
    image: redis:6.2-alpine
    restart: always
    command: --port 6380
    expose:
      - '6380'
    networks:
      - test-app-network

networks:
  test-app-network:
volumes:
  tests:
    driver: local