services:
  app:
    build: .
    restart: on-failure
    depends_on:
      - redis
      - db
    env_file:
      - ./.env
    ports:
      - '8000:8000'
    networks:
      - app-network
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    networks:
      - app-network
    volumes:
      - redis:/var/lib/redis/data
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
    ports:
      - '5432:5432'
    networks:
      - app-network
    volumes:
      - db:/var/lib/postgresql/data

networks:
  app-network:
volumes:
  redis:
    driver: local
  db:
    driver: local