services:
  app:
    build: .
    restart: on-failure
    env_file: project/.env
    depends_on:
      - redis
      - db
    ports:
      - '8000:8000'
    networks:
      - app-network
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    networks:
      - app-network
    volumes:
      - redis:/var/lib/redis/data
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=bohdan
      - POSTGRES_PASSWORD=bohdan1234
      - POSTGRES_DATABASE=bgram
    ports:
      - '5432:5432'
    networks:
      - app-network
    volumes:
      - db:/var/lib/postgresql/data

networks:
  app-network:
volumes:
  redis:
    driver: local
  db:
    driver: local