"""added replayed_message relationship to Message model and added indexes to all relationships

Revision ID: 2a8ee65ccf68
Revises: fc798f3ac774
Create Date: 2022-04-04 23:29:46.536733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a8ee65ccf68'
down_revision = 'fc798f3ac774'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_chat_rooms_photos_chat_room_id'), 'chat_rooms_photos', ['chat_room_id'], unique=False)
    op.create_index(op.f('ix_email_confirmation_tokens_user_id'), 'email_confirmation_tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_message_photos_message_id'), 'message_photos', ['message_id'], unique=False)
    op.add_column('messages', sa.Column('replayed_message_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_messages_author_id'), 'messages', ['author_id'], unique=False)
    op.create_index(op.f('ix_messages_chat_room_id'), 'messages', ['chat_room_id'], unique=False)
    op.create_index(op.f('ix_messages_replayed_message_id'), 'messages', ['replayed_message_id'], unique=False)
    op.drop_constraint('messages_chat_room_id_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'messages', ['replayed_message_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'messages', 'chat_rooms', ['chat_room_id'], ['id'])
    op.drop_column('messages', 'is_read')
    op.create_index(op.f('ix_users_photos_user_id'), 'users_photos', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_photos_user_id'), table_name='users_photos')
    op.add_column('messages', sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_chat_room_id_fkey', 'messages', 'chat_rooms', ['chat_room_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_messages_replayed_message_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_chat_room_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_author_id'), table_name='messages')
    op.drop_column('messages', 'replayed_message_id')
    op.drop_index(op.f('ix_message_photos_message_id'), table_name='message_photos')
    op.drop_index(op.f('ix_email_confirmation_tokens_user_id'), table_name='email_confirmation_tokens')
    op.drop_index(op.f('ix_chat_rooms_photos_chat_room_id'), table_name='chat_rooms_photos')
    # ### end Alembic commands ###
