"""empty message

Revision ID: 86b07e88c82a
Revises: d9530c266101
Create Date: 2022-09-17 23:18:02.641574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86b07e88c82a'
down_revision = 'd9530c266101'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('message_photos_message_id_fkey', 'message_photos', type_='foreignkey')
    op.create_foreign_key('message_photos_message_id_fkey', 'message_photos', 'messages', ['message_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('message_photos_message_id_fkey', 'message_photos', type_='foreignkey')
    op.create_foreign_key('message_photos_message_id_fkey', 'message_photos', 'messages', ['message_id'], ['id'])
    # ### end Alembic commands ###
