"""empty message

Revision ID: d9530c266101
Revises: 465f11749bac
Create Date: 2022-09-12 22:10:43.207327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9530c266101'
down_revision = '465f11749bac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('scheduled_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'scheduled_at')
    # ### end Alembic commands ###
