"""added text field to messages

Revision ID: edfa37aef363
Revises: 0a8739d89c4f
Create Date: 2022-01-04 22:41:25.391740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edfa37aef363'
down_revision = '0a8739d89c4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'text')
    # ### end Alembic commands ###
