"""added relation to chat room in message

Revision ID: fc798f3ac774
Revises: edfa37aef363
Create Date: 2022-01-04 22:55:32.880040

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'fc798f3ac774'
down_revision = 'edfa37aef363'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('chat_room_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'messages', 'chat_rooms', ['chat_room_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'chat_room_id')
    # ### end Alembic commands ###
