on: [push, pull_request]

jobs:
  lint:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install linting dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r linting_requirements.txt

    - name: Check isort
      uses: jamescurtin/isort-action@master

    - name: Check flake8
      run: flake8 .

    - name: Check black
      uses: psf/black@stable

  docker-build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build Docker Image
        run: docker build .